### ISSUE TITLE
CMS166v7 not supported in measures-data.json

### ISSUE THREAD

**Issue by super-jb** [CMSgov/qpp-measures-data#240]
Hello,

Under **qpp-measures-data > measures > 2018 > measures-data.json**, the measure **CMS166v7** isn't supported (not present at all).

And the same measure is supported for 2017 (previous version - **CMS166v6**)
**qpp-measures-data > measures > 2017 > measures-data.json**.

Could someone please take a look at this issue?

Thank you.
**JB**

**Comment by sarahnw** [comment]
Hi JB,

To my knowledge that is not a supported measure for 2018, which is why it is not in the repo.

**Comment by sarahnw** [comment]
@powellc could you post that as feedback to the Developer Google Group? That's the better forum for asks related to the conversion tool: https://groups.google.com/forum/#!forum/qpp-apis

**Comment by powellc** [comment]
For sure @sarahnw. Thanks so much for your prompt help!
