### ISSUE TITLE
null value for measure weight?

### ISSUE THREAD

**Issue by sukhbirsinghRHI** [CMSgov/qpp-measures-data#328]
In the file located at
https://github.com/CMSgov/qpp-measures-data/tree/master/measures/2019/measures-data.json
the data shows that for the 2019 PI_PHCDRR measures (e.g. measure PI_PHCDRR_2) the weight is null.

In the corresponding 2018 measures (when PI used to be ACI), the weight was 5.

Why has this changed? Is this incorrect?

**Comment by michelingle** [comment]
Hi, 

Thank you for your question.  Could you please submit this question as a help desk ticket so that we could route this to the right team to best answer this?  Please email QPP@cms.hhs.gov.  

Thank you!
Michelle
Submissions API Product Support team
