### ISSUE TITLE
measures_data.json for 2021

### ISSUE THREAD

**Issue by iamtheschmitzer** [CMSgov/qpp-measures-data#376]
Can you supply an estimate for when this file will be available? 

TIA

**Comment by iamtheschmitzer** [comment]
The 2021 reporting period I mean

**Comment by iamtheschmitzer** [comment]
The 2021 measure period is practically upon us.  Can someone provide insight as to schedule please?

**Comment by bartcone** [comment]
@iamtheschmitzer Measures will be available in the resource library (https://qpp.cms.gov/about/resource-library) by the end of December. Shortly afterwards it will be made available in measures data in JSON format.

**Comment by iamtheschmitzer** [comment]
Thanks @bartcone
