### ISSUE TITLE
Run with Node js

### ISSUE THREAD

**Issue by vinitpatel03** [CMSgov/qpp-measures-data#47]
I am new to use node js... i dont know hot to integrate with Node js.
I just install Node js with NPM.

Thank You,
Vinit Patel.

**Comment by kencheeto** [comment]
Hi @vinitpatel03 - we only use nodejs for building the measures-data.json and xml files, nodejs is not a runtime dependency of measures data. If you'd like to avoid nodejs/npm altogether, you could use the built files ([raw json](https://raw.githubusercontent.com/CMSgov/qpp-measures-data/master/measures/measures-data.json) or [xml](https://raw.githubusercontent.com/CMSgov/qpp-measures-data/master/measures/measures-data.xml)) directly and watch this repo for updates as needed.

Let me know if you've got any other questions!
