### ISSUE TITLE
CMS 1056 - 2025 Measure Data

### ISSUE THREAD

**Issue by amandakaiser** [CMSgov/qpp-measures-data#825]
We are looking for CMS 1056 in Measures-Date.json for 2025 but it is not listed. Is there a reason it is not included?  We are looking for the following information:
- firstPerformanceYear
- Measure Type
- isHighPriority
Is it patient or Episode based?

**Comment by peg-uehling** [comment]
The new eCQM measures for PY25 will not be added into the measures data .json until later this fall - typically in mid to late November.  However, you can view the measure specification within the eCQI Resource Center.  https://ecqi.healthit.gov/ecqm/ec/2025/cms1056v2?qt-tabs_measure=specifications-and-data-elements

If you have further questions, please submit a help desk ticket so we can route to the right team to best answer.  You can do this by emailing QPP@cms.hhs.gov.

Thanks,
Peg
Submissions API Product Support Team
